"""Purchase database queries."""
from sqlalchemy import func, select
from sqlalchemy.orm import Session, joinedload

from app.models.purchase import Purchase
from app.models.vehicle import Vehicle


class PurchaseRepository:
    def __init__(self, database_session: Session) -> None:
        self.database_session = database_session

    def create_purchase(self, **values: object) -> Purchase:
        purchase = Purchase(**values)
        self.database_session.add(purchase)
        return purchase

    def get_customer_purchase_history(
        self,
        user_id: int,
        *,
        page: int,
        page_size: int,
        make: str | None = None,
        model: str | None = None,
    ) -> tuple[list[Purchase], int]:
        # ── Base statement (no eager-loading) used for both COUNT and data ──
        # Keeping joinedload out of the base avoids PostgreSQL rejecting the
        # COUNT(*) subquery that wraps a statement with a LEFT OUTER JOIN
        # generated by joinedload.
        base = select(Purchase).where(Purchase.user_id == user_id)

        if make or model:
            base = base.join(Vehicle, Purchase.vehicle_id == Vehicle.id)
            if make:
                base = base.where(Vehicle.make.ilike(f"%{make}%"))
            if model:
                base = base.where(Vehicle.model.ilike(f"%{model}%"))

        # COUNT uses the clean base — no joinedload interference
        total = self.database_session.scalar(
            select(func.count()).select_from(base.subquery())
        ) or 0

        # Data query adds joinedload so vehicle fields are available in one query
        purchases = list(
            self.database_session.scalars(
                base.options(joinedload(Purchase.vehicle))
                .order_by(Purchase.created_at.desc(), Purchase.id.desc())
                .offset((page - 1) * page_size)
                .limit(page_size)
            )
        )
        return purchases, total

    def get_revenue_summary(self) -> tuple[object, int, int]:
        stmt = select(
            func.coalesce(func.sum(Purchase.total_price), 0),
            func.coalesce(func.sum(Purchase.quantity), 0),
            func.count(Purchase.id),
        )
        result = self.database_session.execute(stmt).one()
        return result[0], int(result[1]), int(result[2])

